# Currently serves the purpose to build RocksDB 10.10.1 reducing CI check completion time

name: Build CI image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - deployments/docker/Dockerfile.ci

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: deployments/docker/Dockerfile.ci
          push: true
          tags: ghcr.io/masamasaowl/vyomanaut-ci:rocksdb-10.10.1